# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: Apache-2.0
# ==-----------------------------------------------------------== #

# Reuse annotations file.
#
# This file controls how reuse-tool finds copyright and license notices within
# source files.
# See https://reuse.software and https://github.com/fsfe/reuse-tool for more
# details.
# We currently use reuse-tool version 5.0.2.

version = 1

[[annotations]]
path = [
  "PklProject.deps.json",
  "tests/*.pcf",
  "tools/stdschema.pkl.ci/PklProject.deps.json",
]
precedence = "override"
SPDX-FileCopyrightText = "© 2025 Nayan Patil <nayantsg@proton.me>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["COPYRIGHT", "THIRD-PARTY-NOTICES"]
precedence = "override"
SPDX-FileCopyrightText = "© 2025 Nayan Patil <nayantsg@proton.me>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["gradle/wrapper/gradle-wrapper.jar"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright © 2015-2021 the original authors"
SPDX-License-Identifier = "Apache-2.0"
